# Generated by Django 4.0.5 on 2022-07-06 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('pcode', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(default='Question Name', max_length=255)),
                ('pdesc', models.TextField()),
                ('difficulty', models.CharField(max_length=200)),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('input_TC', models.TextField()),
                ('output_TC', models.TextField()),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('pcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ojmain.problems', verbose_name='problem_id')),
                ('imp', models.TextField()),
                ('out', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verdicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_status', models.CharField(max_length=200)),
                ('pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojmain.problems', verbose_name='problem_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojmain.userprofile', verbose_name='verdict_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('scode', models.AutoField(primary_key=True, serialize=False)),
                ('vrt', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojmain.problems', verbose_name='problem_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojmain.userprofile', verbose_name='user.id')),
            ],
        ),
    ]
