# Generated by Django 4.0.5 on 2022-07-07 09:15

from django.db import migrations, models
import django_monaco_editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('ojmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', django_monaco_editor.models.MonacoEditorModelField()),
            ],
        ),
    ]
